on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - run: sudo apt-get update && sudo apt-get install -y cppcheck
    - run: cppcheck search --enable=all --inconclusive #--error-exitcode=1
    - run: sudo apt-get update && sudo apt-get install -y clang-tidy 
    - run: clang-tidy search/**/* -- || true
    - run: sudo apt-get update && sudo apt-get install -y libgtest-dev
    - run: chmod +x test.sh && ./test.sh
    #- run: sudo apt-get update && sudo apt-get install -y valgrind 
    #- run: valgrind --tool=memcheck --leak-check=yes ./search
    #  working-directory: search/build
