on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - run: sudo apt-get update && sudo apt-get install -y libgtest-dev
    - run: rm -rf build
      working-directory: matrix
    - run: mkdir build
      working-directory: matrix
    - run: cmake ..
      working-directory: matrix/build
    - run: cmake --build .
      working-directory: matrix/build
